version: '3.7'
services:
  app:
    build: ./shortener
    command: flask run
    env_file:
      - ./shortener/.env
    ports:
      - "5000:5000"
    volumes:
      - ./shortener:/opt/app
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - ./db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=flask
      - POSTGRES_PASSWORD=pleasegivebetteroneinproduction
      - POSTGRES_DB=development

volumes:
  db: